Commit Assignment 2

diff --git a/.github/workflows/calculator_pipeline.yml b/.github/workflows/calculator_pipeline.yml
--- a/.github/workflows/calculator_pipeline.yml
+++ b/.github/workflows/calculator_pipeline.yml
@@ -24,16 +24,53 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      # Step 2: Log in to the Azure Container Registry
+      # step 2///////////////////////
+      # Set up environment
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.12'
+
+      - name: Install dependencies
+        run: |
+          pip3 install -r requirements.txt
+          pip3 install openapi-python-client
+      
+      # Start REST API
+      - name: Start REST API
+        run: |
+          python3 BE/calculator.py --rest &
+      
+      - name: Wait for API to be ready
+        run: |
+          sleep 10  # Adjust as needed to ensure the API is up
+      
+      # Run tests
+      - name: Run tests
+        id: run-tests
+        run: |
+          pytest --junit-xml=report.xml
+      
+      # Publishes a test report in JUnit format
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/report.xml'
+      #/////////////////////////////////
+
+      # Step 3: Log in to the Azure Container Registry
       - name: Login to Azure Container Registry
+        if: success() # Only proceed if previous steps were successful
         uses: docker/login-action@v2
         with:
           registry: judevops.azurecr.io
           username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
           password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
 
-      # Step 3: Build and push the Docker image
+      # Step 4: Build and push the Docker image
       - name: Build and push Docker image
+        if: success()  # Only proceed if previous steps were successful
         run: |
           docker build -t judevops.azurecr.io/amela_music-calculator -f BE/Dockerfile BE
           docker push judevops.azurecr.io/amela_music-calculator
